// Project data for the game — all 8 projects with enriched details + mockup images

export const gameProjects = [
  {
    id: 'skillsprint',
    title: 'SkillSprint AI',
    description: 'AI-powered learning platform that personalizes skill development paths and accelerates professional growth.',
    problem: 'Generic online learning platforms give every user the same course path, wasting time on skills they already have.',
    solution: 'Built an NLP-powered engine that analyzes a user\'s current skill level and crafts a personalized, adaptive learning path — cutting time-to-mastery significantly.',
    tech: ['AI/ML', 'Python', 'NLP', 'Personalization'],
    link: 'https://github.com/jayesh55555/SkillSprint-AI',
    image: '/images/projects/skillsprint.png',
    type: 'cloud' as const,
  },
  {
    id: 'foodscanner',
    title: 'Food Label Scanner',
    description: 'AI-powered mobile app that scans food labels to provide instant nutritional information and health insights.',
    problem: 'Most people can\'t decode the tiny text and complex ingredients on food packaging in real-time while shopping.',
    solution: 'Deployed OCR + Computer Vision to extract label text from camera frames and matched against a nutritional database — delivering instant health scores and allergen warnings.',
    tech: ['Computer Vision', 'OCR', 'Mobile', 'AI/ML'],
    link: 'https://github.com/jayesh55555/Food-Label-Scanner',
    image: '/images/projects/foodscanner.png',
    type: 'balloon' as const,
  },
  {
    id: 'knowledge',
    title: 'Knowledge Graph',
    description: 'An AI-powered knowledge graph builder that transforms unstructured text into structured entity-relationships.',
    problem: 'Extracting structured, queryable knowledge from large volumes of raw text is a manual and time-intensive process.',
    solution: 'Applied spaCy NLP + custom entity recognition to auto-extract entities and relationships, then visualized them as an interactive knowledge graph — turning docs into databases.',
    tech: ['Python', 'NLP', 'spaCy', 'Graph DB'],
    link: 'https://github.com/jayesh55555/Knowledge_graph',
    image: '/images/projects/knowledge.png',
    type: 'card' as const,
  },
  {
    id: 'cinexus',
    title: 'CINEXUS Movies',
    description: 'Full-stack intelligent movie reservation system using Django, AWS, and ML to enhance user experiences.',
    problem: 'Traditional movie booking apps lack personalization — users scroll through hundreds of movies without smart recommendations.',
    solution: 'Built a Django + PostgreSQL reservation platform with collaborative-filtering recommendations, hosted on AWS EC2/RDS with a clean seat-selection UI.',
    tech: ['Django', 'Python', 'AWS', 'PostgreSQL'],
    link: 'https://github.com/jayesh55555/CINEXUS-Movie-Reservation',
    image: '/images/projects/cinexus.png',
    type: 'cloud' as const,
  },
  {
    id: 'cardprocessing',
    title: 'Card Processing',
    description: 'A comprehensive credit card processing system with secure transaction handling and validation.',
    problem: 'Understanding how payment processing pipelines work at a deep level — validation, fraud checks, and transaction states — is complex to implement correctly.',
    solution: 'Built a full Java OOP simulation of a credit card lifecycle — from card issuing to transaction authorization, validation, and secure ledger recording.',
    tech: ['Java', 'OOP', 'Security', 'Data Structures'],
    link: 'https://github.com/jayesh55555/Credit-Card-Processing-System',
    image: '/images/projects/cardprocessing.png',
    type: 'balloon' as const,
  },
  {
    id: 'barcode',
    title: 'Barcode Generator',
    description: 'Django and Python-powered website for registering, searching, and generating barcodes for any product.',
    problem: 'Small businesses and inventory managers need a quick way to register products and generate scannable barcodes without expensive tools.',
    solution: 'Created a Django web app with a barcode generation library — users register products, search inventory, and download print-ready barcode images instantly.',
    tech: ['Django', 'Python', 'Barcode API', 'PostgreSQL'],
    link: 'https://github.com/jayesh55555/Product-Barcode-Generator',
    image: '/images/projects/barcode.png',
    type: 'card' as const,
  },
  {
    id: 'doorwin',
    title: 'DoorWin Detector',
    description: 'A YOLOv5 model to detect doors and windows in floor plans with custom dataset training.',
    problem: 'Architects and construction software need automated detection of structural elements in floor plans — manually annotating blueprints is slow and error-prone.',
    solution: 'Trained a custom YOLOv5 object detection model on annotated floor plan images — achieving accurate real-time detection of doors and windows from raw blueprint images.',
    tech: ['YOLOv5', 'Computer Vision', 'PyTorch', 'Custom Dataset'],
    link: 'https://github.com/jayesh55555/window-door_detection',
    image: '/images/projects/doorwin.png',
    type: 'cloud' as const,
  },
  {
    id: 'amber',
    title: 'Amber Designer',
    description: 'Full-stack platform for accessible, on-demand apparel rental bookings.',
    problem: 'Fashion rental is expensive and inaccessible — customers can\'t easily browse, book, and pay for designer outfits online.',
    solution: 'Shipped a full-stack e-commerce platform with booking calendar, Razorpay payment gateway integration, and a curated catalog — live at amber-designer-pay.vercel.app.',
    tech: ['Full-Stack', 'React', 'Node.js', 'Payment Gateway'],
    link: 'https://amber-designer-pay.vercel.app/',
    image: '/images/projects/amber.png',
    type: 'balloon' as const,
  },
];
